name: dance-recognition
channels:
  - pytorch
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.8.0=hb921021_15
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h173a860_6
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.7=hf454442_0
  - aws-c-sdkutils=0.2.1=h4e1184b_4
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.7=hd92328a_7
  - aws-sdk-cpp=1.11.458=hc430e4a_4
  - backports.zstd=1.3.0=py311h6b1f9c4_0
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_4
  - blas=1.0=mkl
  - brotli-python=1.1.0=py311h1ddb823_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachetools=7.0.1=pyhd8ed1ab_0
  - cccl=2.3.2=h6103f9b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h5b438cf_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - contourpy=1.3.3=py311h724c32c_4
  - cpython=3.11.14=py311hd8ed1ab_3
  - cuda-bindings=12.9.5=py311hff0572f_0
  - cuda-cccl=12.4.127=ha770c72_2
  - cuda-cccl_linux-64=12.4.127=ha770c72_2
  - cuda-crt-dev_linux-64=12.4.131=ha770c72_1
  - cuda-crt-tools=12.4.131=ha770c72_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-dev_linux-64=12.4.127=h85509e4_2
  - cuda-cudart-static_linux-64=12.4.127=h85509e4_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvcc-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvcc-impl=12.4.131=hd3aeb46_1
  - cuda-nvcc-tools=12.4.131=hd3aeb46_1
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvm-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvvm-impl=12.4.131=h59595ed_1
  - cuda-nvvm-tools=12.4.131=h59595ed_1
  - cuda-opencl=12.4.127=0
  - cuda-pathfinder=1.3.3=pyhcf101f3_0
  - cuda-profiler-api=12.4.127=ha770c72_2
  - cuda-python=12.9.5=pyh698daf1_0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.4=h3060b56_3
  - cudf=25.08.00=cuda12_py311_250806_6cea3743
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cuml=25.08.00=cuda12_py311_250806_b081fcd0
  - cupy=13.6.0=py311h72da3fd_2
  - cupy-core=13.6.0=py311he30c881_2
  - cytoolz=1.1.0=py311h49ec1c0_1
  - dask-core=2025.7.0=pyhe01879c_1
  - dask-cudf=25.08.00=cuda12_py311_250806_6cea3743
  - dataclasses=0.8=pyhc8e2a94_3
  - distributed-ucxx=0.45.01=py_250806_c25d2cdb_h7e233d3
  - dlpack=0.8=h59595ed_3
  - fastrlock=0.8.3=py311hc665b79_2
  - ffmpeg=4.4.0=hca11adc_2
  - filelock=3.20.3=pyhd8ed1ab_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - gnutls=3.6.13=h85f3911_1
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hupper=1.12.1=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - iopath=0.1.10=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - kernel-headers_linux-64=4.18.0=he073ed8_9
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - legacy-cgi=2.6.4=pyhcf101f3_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarrow=15.0.2=hb96de33_49_cpu
  - libarrow-acero=15.0.2=h7599340_49_cpu
  - libarrow-dataset=15.0.2=h7599340_49_cpu
  - libarrow-flight=15.0.2=hcd252ac_49_cpu
  - libarrow-flight-sql=15.0.2=hc7d262c_49_cpu
  - libarrow-gandiva=15.0.2=h30dee1a_49_cpu
  - libarrow-substrait=15.0.2=hc7d262c_49_cpu
  - libblas=3.9.0=26_linux64_mkl
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=26_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcudf=25.08.00=cuda12_250806_6cea3743
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcuml=25.08.00=cuda12_250806_b081fcd0
  - libcumlprims=25.08.00=cuda12_py310_250806_59064b25
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libcuvs=25.08.00=cuda12_250806_9ce11a0f
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_17
  - libgoogle-cloud=2.32.0=h804f50b_0
  - libgoogle-cloud-storage=2.32.0=h0121fbd_0
  - libgrpc=1.67.1=hc2c308b_0
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkvikio=25.08.00=cuda12_9_250806_2f72c39a
  - liblapack=3.9.0=26_linux64_mkl
  - libllvm17=17.0.6=hc9c083f_1
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libmagma=2.8.0=h0af6554_0
  - libmagma_sparse=2.8.0=h0af6554_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvcomp=4.2.0.11=hb7e823c_1
  - libnvcomp-dev=4.2.0.11=hb7e823c_1
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libparquet=15.0.2=h3fef80f_49_cpu
  - libpng=1.6.55=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libraft=25.08.00=cuda12_250806_2fb92393
  - libraft-headers=25.08.00=cuda12_250806_2fb92393
  - libraft-headers-only=25.08.00=cuda12_250806_2fb92393
  - libre2-11=2024.07.02=hbbce691_2
  - librmm=25.08.00=cuda12_250806_63a4d366
  - libsanitizer=11.4.0=h5763a12_13
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libsystemd0=257.10=hd0affe5_4
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtorch=2.5.1=cuda120_h6f417b9_303
  - libucxx=0.45.01=cuda12_250806_c25d2cdb
  - libudev1=257.10=hd0affe5_4
  - libutf8proc=2.9.0=hb9d3cd8_1
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311h1c460e0_1
  - lz4-c=1.10.0=h5888daf_1
  - magma=2.8.0=h51420fd_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3778330_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2024.2.2=ha770c72_17
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311hdf67eae_1
  - narwhals=2.16.0=pyhcf101f3_0
  - nccl=2.29.3.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.6.1=pyhcf101f3_0
  - ninja=1.13.2=h171cf75_0
  - numba=0.61.2=py311h6220fa4_2
  - nvtx=0.2.14=py311h49ec1c0_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.1=h35e630c_1
  - orc=2.0.3=h97ab989_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py311hed34c8f_2
  - partd=1.4.2=pyhd8ed1ab_0
  - pastedeploy=3.1.0=pyhd8ed1ab_1
  - pip=26.0=pyh8b19718_0
  - plaster=1.0=pyhd8ed1ab_1
  - plaster_pastedeploy=0.7=pyhd8ed1ab_1
  - portalocker=3.2.0=py311h38be061_1
  - psutil=7.2.2=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibcudf=25.08.00=cuda12_py311_250806_6cea3743
  - pylibraft=25.08.00=cuda12_py311_250806_2fb92393
  - pynvjitlink=0.7.0=12.9_py311_250625_3693c9cd_hd6618c4
  - pynvml=12.0.0=pyhd8ed1ab_0
  - pyramid=2.0.2=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hfe2f287_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=cuda120_py311h7a71dd8_303
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_1
  - raft-dask=25.08.00=cuda12_py311_250806_2fb92393
  - rapids=0.0.1=pyh9f0ad1d_0
  - rdma-core=61.0=h192683f_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.2=pyhcf101f3_0
  - rmm=25.08.00=cuda12_py311_250806_63a4d366
  - s2n=1.5.11=h072c03f_0
  - scikit-learn=1.5.2=py311h57cc02b_1
  - scipy=1.16.3=py311hbe70eeb_2
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.28=h4ee821c_9
  - tabulate=0.9.0=pyhcf101f3_3
  - tbb=2021.13.0=hb700be7_5
  - tblib=3.2.2=pyhcf101f3_0
  - termcolor=3.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h366c992_103
  - toolz=1.1.0=pyhd8ed1ab_1
  - torchaudio=2.5.1=py311_cu124
  - tqdm=4.67.3=pyh8f84b5b_0
  - translationstring=1.4=pyhd8ed1ab_1
  - treelite=4.4.1=py311hd96400b_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucx=1.17.0=h1b0e7dc_4
  - ucx-py=0.45.00=py311_250806_d53bdda0
  - ucxx=0.45.01=cuda12_py311_250806_c25d2cdb
  - urllib3=2.5.0=pyhd8ed1ab_0
  - venusian=3.1.1=pyhd8ed1ab_1
  - webob=1.8.9=pyhd8ed1ab_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zope.deprecation=4.4.0=py_0
  - zope.interface=8.0.1=py311haee01d2_1
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - bokeh==3.6.3
      - colorcet==3.1.0
      - cucim-cu12==26.2.0
      - cuda-core==0.5.1
      - cuda-toolkit==12.9.1
      - cudf-cu12==26.2.1
      - cugraph-cu12==26.2.0
      - cuvs-cu12==26.2.0
      - cuxfilter-cu12==26.2.0
      - cycler==0.12.1
      - dask==2026.1.1
      - dask-cuda==26.2.0
      - dask-cudf-cu12==26.2.1
      - datashader==0.18.2
      - defusedxml==0.7.1
      - distributed==2026.1.1
      - distributed-ucxx-cu12==0.48.0
      - fastapi==0.128.6
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - fonttools==4.61.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - geopandas==1.1.2
      - glcontext==3.0.0
      - gradio==6.5.1
      - gradio-client==2.0.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - holoviews==1.20.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-server==2.17.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - libcudf-cu12==26.2.1
      - libcugraph-cu12==26.2.0
      - libcuvs-cu12==26.2.0
      - libkvikio-cu12==26.2.0
      - libraft-cu12==26.2.0
      - libucx-cu12==1.19.0
      - libucxx-cu12==0.48.0
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - markdown==3.10.2
      - matplotlib==3.10.8
      - mdit-py-plugins==0.5.0
      - mistune==3.2.0
      - moderngl==5.12.0
      - moge==2.0.0
      - multidict==6.7.1
      - multipledispatch==1.0.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - numba-cuda==0.27.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-libnvcomp-cu12==5.1.0.21
      - nvidia-ml-py==13.590.48
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvimgcodec-cu12==0.7.0.11
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - nx-cugraph-cu12==26.2.0
      - opencv-python==4.13.0.92
      - orjson==3.11.7
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - panel==1.7.5
      - param==2.3.2
      - pillow==12.1.1
      - pipeline==1.0.0
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - propcache==0.4.1
      - ptyprocess==0.7.0
      - pyarrow==23.0.0
      - pyct==0.6.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pylibcudf-cu12==26.2.1
      - pylibcugraph-cu12==26.2.0
      - pylibraft-cu12==26.2.0
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.2
      - python-json-logger==4.0.0
      - python-multipart==0.0.22
      - pytorch3d==0.7.9
      - pyviz-comms==3.0.6
      - pyzmq==27.1.0
      - raft-dask-cu12==26.2.0
      - rapids-dask-dependency==26.2.0
      - rapids-logger==0.2.3
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safehttpx==0.1.7
      - scikit-image==0.25.2
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - simpervisor==1.0.0
      - soupsieve==2.8.3
      - starlette==0.52.1
      - terminado==0.18.1
      - tifffile==2026.1.28
      - tinycss2==1.4.0
      - tomlkit==0.13.3
      - torch==2.10.0
      - torchvision==0.25.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - trimesh==4.11.1
      - triton==3.6.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - uc-micro-py==1.0.3
      - ucxx-cu12==0.48.0
      - uri-template==1.3.0
      - utils3d==1.3
      - uvicorn==0.40.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - xarray==2026.1.0
      - yarl==1.22.0
prefix: /home/sogang/mnt/db_2/anaconda3/envs/dance-recognition
